In [1]:
import numpy as np
import pandas as pd

# Исходный Data Frame

In [2]:
path = './_data.csv'
data = pd.read_csv(path)
part_1 = data.iloc[:, :13]
part_1.head()

,Unnamed: 0,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт

# Преобразование названий колонок

In [3]:
part_1.columns = ['Serial_number', 'Announcement ID', 'Number_of_rooms', 'Type', 'Metro', 'Address', 'Area,m2', 'Building_info', 'Parking', 'Price', 'Phone_number', 'Description', 'Interior_finishing']

In [4]:
part_1.head()

,Serial_number,Announcement ID,Number_of_rooms,Type,Metro,Address,"Area,m2",Building_info,Parking,Price,Phone_number,Description,Interior_finishing
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт

# Избавляемся от пропусков

In [5]:
part_1_re = part_1
part_1_re['Price'] = part_1_re['Price'].str.split(' ').str[0]
part_1_re['Area,m2'] = part_1_re['Area,m2'].str.split('/').str[0]
part_1_re['Number_of_rooms'] = part_1_re['Number_of_rooms'].str.split(',').str[0]
part_1_re['Price'] = pd.to_numeric(part_1_re['Price'], errors='coerce')
part_1_re['Area,m2'] = pd.to_numeric(part_1_re['Area,m2'], errors='coerce')
part_1_re['Number_of_rooms'] = pd.to_numeric(part_1_re['Number_of_rooms'], errors='coerce')
part_1_re.head()

,Serial_number,Announcement ID,Number_of_rooms,Type,Metro,Address,"Area,m2",Building_info,Parking,Price,Phone_number,Description,Interior_finishing
0,0,271271157,4.0,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0,"5/16, Монолитный",подземная,500000.0,+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский
1,1,271634126,4.0,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0,"5/16, Монолитно-кирпичный",подземная,500000.0,+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский
2,2,271173086,4.0,Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0,5/16,подземная,500000.0,"+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт
3,3,272197456,4.0,Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0,5/6,подземная,400000.0,"+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт
4,4,273614615,2.0,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0,"12/26, Панельный",NaN,225000.0,+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт

In [6]:
# Заолним пропуски в колонке Number_of_rooms средним значением
part_1_re['Number_of_rooms'] = part_1_re['Number_of_rooms'].fillna(int(part_1_re['Number_of_rooms'].mean()))

In [8]:
# Заполним пропуски в категориальных признаках модой
part_1_re['Metro'] = part_1_re['Metro'].fillna(part_1_re['Metro'].mode()[0])
part_1_re['Parking'] = part_1_re['Parking'].fillna(part_1_re['Parking'].mode()[0])
part_1_re['Interior_finishing'] = part_1_re['Interior_finishing'].fillna(part_1_re['Interior_finishing'].mode()[0])

,Serial_number,Announcement ID,Number_of_rooms,Type,Metro,Address,"Area,m2",Building_info,Parking,Price,Phone_number,Description,Interior_finishing
0,0,271271157,4.0,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0,"5/16, Монолитный",подземная,500000.0,+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский
1,1,271634126,4.0,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0,"5/16, Монолитно-кирпичный",подземная,500000.0,+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский
2,2,271173086,4.0,Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0,5/16,подземная,500000.0,"+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт
3,3,272197456,4.0,Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0,5/6,подземная,400000.0,"+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт
4,4,273614615,2.0,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0,"12/26, Панельный",наземная,225000.0,+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт

In [10]:
part_1_re.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23368 entries, 0 to 23367
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Serial_number       23368 non-null  int64
 1   Announcement ID     23368 non-null  int64
 2   Number_of_rooms     23368 non-null  float64
 3   Type                23368 non-null  object
 4   Metro               23368 non-null  object
 5   Address             23368 non-null  object
 6   Area,m2             23368 non-null  float64
 7   Building_info       23368 non-null  object
 8   Parking             23368 non-null  object
 9   Price               23368 non-null  float64
 10  Phone_number        23368 non-null  object
 11  Description         23368 non-null  object
 12  Interior_finishing  23368 non-null  object
dtypes: float64(3), int64(2), object(8)
memory usage: 2.3+ MB

In [11]:
part_1_re.describe()

,Serial_number,Announcement ID,Number_of_rooms,"Area,m2",Price
count,23368.000000,2.336800e+04,23368.000000,23368.000000,2.336800e+04
mean,11683.500000,2.676265e+08,2.013266,62.819425,8.289414e+04
std,6745.904881,1.876862e+07,0.978038,46.699425,1.226962e+05
min,0.000000,1.072986e+08,1.000000,7.000000,5.000000e+03
25%,5841.750000,2.712663e+08,1.000000,38.000000,3.700000e+04
50%,11683.500000,2.739030e+08,2.000000,48.000000,4.950000e+04
75%,17525.250000,2.746872e+08,3.000000,70.000000,7.500000e+04
max,23367.000000,2.750064e+08,6.000000,811.000000,3.000000e+06

In [12]:
part_1_re.describe(include=['object'])

,Type,Metro,Address,Building_info,Parking,Phone_number,Description,Interior_finishing
count,23368,23368,23368,23368,23368,23368,23368,23368
unique,1,5866,12850,2565,5,13172,23078,4
top,Квартира,м. Академическая (10 мин пешком),"Москва, Чапаевский переулок, 3","3/5, Кирпичный",наземная,+79819217172,0,Косметический
freq,23368,1356,63,322,19460,302,108,11254